export interface MetricDefinition {
  title: string;
  description: string;
  unit?: string;
}

export const metricGlossary: Record<string, MetricDefinition> = {
  completedRevenue: {
    title: "Completed Revenue",
    description: "Total revenue from successfully processed and settled payments. This represents money that has been cleared by the payment processor and is available in your account.",
    unit: "IDR"
  },
  pendingRevenue: {
    title: "Pending Revenue",
    description: "Revenue from payments that have been authorized but not yet captured or settled. These transactions are awaiting final processing.",
    unit: "IDR"
  },
  refundedRevenue: {
    title: "Refunded Revenue",
    description: "Total amount of money returned to customers through refunds. This reduces your overall revenue.",
    unit: "IDR"
  },
  totalRevenue: {
    title: "Total Revenue",
    description: "The sum of all completed payments before any refunds or deductions. This represents your gross revenue.",
    unit: "IDR"
  },
  activeSubscriptions: {
    title: "Active Subscriptions",
    description: "Number of merchants currently on a paid subscription plan with an active billing cycle.",
  },
  trialSubscriptions: {
    title: "Trial Subscriptions",
    description: "Number of merchants currently in their free trial period. These may convert to paid subscriptions.",
  },
  expiredSubscriptions: {
    title: "Expired Subscriptions",
    description: "Number of merchants whose subscription or trial has ended and has not been renewed.",
  },
  bandwidth: {
    title: "Bandwidth Usage",
    description: "Real-time data transfer rate measuring the amount of data being sent and received by the platform, including messages, media files, and API responses.",
    unit: "KB/s"
  },
  customersServed: {
    title: "Customers Served",
    description: "Number of unique customer sessions actively receiving support per second. This indicates the real-time load on the customer service system.",
    unit: "/sec"
  },
  totalConversations: {
    title: "Total Conversations",
    description: "Total number of chat sessions initiated across all merchants. Each conversation represents a unique customer interaction.",
  },
  aiResponses: {
    title: "AI Responses",
    description: "Number of responses generated by the AI chatbot. Higher numbers indicate effective automation of customer support.",
  },
  humanEscalations: {
    title: "Human Escalations",
    description: "Number of conversations transferred from AI to human supervisors. Lower rates typically indicate better AI performance.",
  },
  avgResponseTime: {
    title: "Average Response Time",
    description: "Mean time taken to respond to customer messages, including both AI and human responses. Lower is better.",
    unit: "seconds"
  },
  satisfactionRate: {
    title: "Satisfaction Rate",
    description: "Percentage of customers who rated their support experience positively. Based on post-conversation surveys.",
    unit: "%"
  },
  resolutionRate: {
    title: "Resolution Rate",
    description: "Percentage of conversations successfully resolved without requiring multiple follow-ups.",
    unit: "%"
  },
  dataUsage: {
    title: "Data Usage",
    description: "Total amount of data consumed by merchant operations including messages, media uploads, and API calls.",
    unit: "MB"
  },
  messageVolume: {
    title: "Message Volume",
    description: "Total number of messages exchanged across all conversations in the selected time period.",
  },
  merchantGrowth: {
    title: "Merchant Growth",
    description: "Rate of new merchant registrations compared to the previous period. Positive values indicate platform growth.",
    unit: "%"
  },
  churnRate: {
    title: "Churn Rate",
    description: "Percentage of merchants who cancelled or did not renew their subscriptions. Lower is better.",
    unit: "%"
  },
  conversionRate: {
    title: "Conversion Rate",
    description: "Percentage of trial users who converted to paid subscriptions. Higher rates indicate effective onboarding.",
    unit: "%"
  },
  weekOverWeek: {
    title: "Week over Week",
    description: "Comparison of current week's metrics against the previous week. Shows short-term trends.",
    unit: "%"
  },
  monthOverMonth: {
    title: "Month over Month",
    description: "Comparison of current month's metrics against the previous month. Shows medium-term trends.",
    unit: "%"
  },
  activeMerchants: {
    title: "Active Merchants",
    description: "Number of merchants who have had at least one conversation in the last 30 days.",
  },
  inactiveMerchants: {
    title: "Inactive Merchants",
    description: "Number of registered merchants with no activity in the last 30 days. May require re-engagement.",
  },
  apiCalls: {
    title: "API Calls",
    description: "Total number of API requests made to the platform, including widget integrations and dashboard operations.",
  },
  storageUsed: {
    title: "Storage Used",
    description: "Total disk space consumed by uploaded files, media, and knowledge base content.",
    unit: "GB"
  },
};

export function getMetricInfo(key: string): MetricDefinition {
  return metricGlossary[key] || {
    title: key.replace(/([A-Z])/g, ' $1').trim(),
    description: "No description available for this metric.",
  };
}
