export interface MetricDefinition {
  title: string;
  description: string;
  unit?: string;
}

export const metricGlossary: Record<string, MetricDefinition> = {
  completedRevenue: {
    title: "Completed Revenue",
    description: "Total revenue from successfully processed and settled payments. This represents money that has been cleared by the payment processor and is available in your account.",
    unit: "IDR"
  },
  pendingRevenue: {
    title: "Pending Revenue",
    description: "Revenue from payments that have been authorized but not yet captured or settled. These transactions are awaiting final processing.",
    unit: "IDR"
  },
  refundedRevenue: {
    title: "Refunded Revenue",
    description: "Total amount of money returned to customers through refunds. This reduces your overall revenue.",
    unit: "IDR"
  },
  totalRevenue: {
    title: "Total Revenue",
    description: "The sum of all completed payments before any refunds or deductions. This represents your gross revenue.",
    unit: "IDR"
  },
  activeSubscriptions: {
    title: "Active Subscriptions",
    description: "Number of merchants currently on a paid subscription plan with an active billing cycle.",
  },
  trialSubscriptions: {
    title: "Trial Subscriptions",
    description: "Number of merchants currently in their free trial period. These may convert to paid subscriptions.",
  },
  expiredSubscriptions: {
    title: "Expired Subscriptions",
    description: "Number of merchants whose subscription or trial has ended and has not been renewed.",
  },
  bandwidth: {
    title: "Bandwidth Usage",
    description: "Real-time data transfer rate measuring the amount of data being sent and received by the platform, including messages, media files, and API responses.",
    unit: "KB/s"
  },
  customersServed: {
    title: "Customers Served",
    description: "Number of unique customer sessions actively receiving support per second. This indicates the real-time load on the customer service system.",
    unit: "/sec"
  },
  totalConversations: {
    title: "Total Conversations",
    description: "Total number of chat sessions initiated across all merchants. Each conversation represents a unique customer interaction.",
  },
  aiResponses: {
    title: "AI Responses",
    description: "Number of responses generated by the AI chatbot. Higher numbers indicate effective automation of customer support.",
  },
  humanEscalations: {
    title: "Human Escalations",
    description: "Number of conversations transferred from AI to human supervisors. Lower rates typically indicate better AI performance.",
  },
  avgResponseTime: {
    title: "Average Response Time",
    description: "Mean time taken to respond to customer messages, including both AI and human responses. Lower is better.",
    unit: "seconds"
  },
  satisfactionRate: {
    title: "Satisfaction Rate",
    description: "Percentage of customers who rated their support experience positively. Based on post-conversation surveys.",
    unit: "%"
  },
  resolutionRate: {
    title: "Resolution Rate",
    description: "Percentage of conversations successfully resolved without requiring multiple follow-ups.",
    unit: "%"
  },
  dataUsage: {
    title: "Data Usage",
    description: "Total amount of data consumed by merchant operations including messages, media uploads, and API calls.",
    unit: "MB"
  },
  messageVolume: {
    title: "Message Volume",
    description: "Total number of messages exchanged across all conversations in the selected time period.",
  },
  merchantGrowth: {
    title: "Merchant Growth",
    description: "Rate of new merchant registrations compared to the previous period. Positive values indicate platform growth.",
    unit: "%"
  },
  churnRate: {
    title: "Churn Rate",
    description: "Percentage of merchants who cancelled or did not renew their subscriptions. Lower is better.",
    unit: "%"
  },
  conversionRate: {
    title: "Conversion Rate",
    description: "Percentage of trial users who converted to paid subscriptions. Higher rates indicate effective onboarding.",
    unit: "%"
  },
  weekOverWeek: {
    title: "Week over Week",
    description: "Comparison of current week's metrics against the previous week. Shows short-term trends.",
    unit: "%"
  },
  monthOverMonth: {
    title: "Month over Month",
    description: "Comparison of current month's metrics against the previous month. Shows medium-term trends.",
    unit: "%"
  },
  activeMerchants: {
    title: "Active Merchants",
    description: "Number of merchants who have had at least one conversation in the last 30 days.",
  },
  inactiveMerchants: {
    title: "Inactive Merchants",
    description: "Number of registered merchants with no activity in the last 30 days. May require re-engagement.",
  },
  apiCalls: {
    title: "API Calls",
    description: "Total number of API requests made to the platform, including widget integrations and dashboard operations.",
  },
  storageUsed: {
    title: "Storage Used",
    description: "Total disk space consumed by uploaded files, media, and knowledge base content.",
    unit: "GB"
  },
  totalMerchants: {
    title: "Total Merchants",
    description: "Total number of businesses registered on the Chatvice platform. Includes both active and inactive accounts across all subscription tiers.",
  },
  totalCustomers: {
    title: "Total Customers",
    description: "Cumulative count of unique end-users who have interacted with chatbots across all merchants. Each customer is counted once regardless of multiple conversations.",
  },
  aiResolutions: {
    title: "AI Resolutions",
    description: "Percentage of customer inquiries successfully resolved by the AI without requiring human escalation. Higher values indicate effective AI training and knowledge base coverage.",
    unit: "%"
  },
  avgRespondTime: {
    title: "Average Response Time",
    description: "Mean time between a customer sending a message and receiving a response. Includes both AI (typically <2s) and human supervisor responses. Lower times improve customer satisfaction.",
    unit: "seconds"
  },
  globalBandwidth: {
    title: "Global Bandwidth (Chatvice)",
    description: "Total data transfer across the entire Chatvice platform including all merchants, API calls, media uploads, and real-time communications.",
    unit: "GB"
  },
  merchantBandwidth: {
    title: "Merchant Bandwidth",
    description: "Data transfer used by this specific merchant including chat messages, media files, knowledge base content, and widget interactions.",
    unit: "MB"
  },
  globalStorage: {
    title: "Global Storage (Chatvice)",
    description: "Total storage consumed across all merchants on the platform including knowledge base content, uploaded media, and conversation history.",
    unit: "GB"
  },
  merchantStorage: {
    title: "Merchant Storage",
    description: "Storage used by this specific merchant for their knowledge base, uploaded files, and conversation archives.",
    unit: "MB"
  },
  globalApiCalls: {
    title: "Global API Calls (Chatvice)",
    description: "Total API requests processed by the Chatvice platform across all merchants and integrations.",
  },
  merchantApiCalls: {
    title: "Merchant API Calls",
    description: "Number of API requests made by this specific merchant's widget and dashboard operations.",
  },
  freePlanMerchants: {
    title: "Free Plan Merchants",
    description: "Number of merchants on the free tier with limited features. These accounts may convert to paid plans.",
  },
  starterPlanMerchants: {
    title: "Starter Plan Merchants",
    description: "Number of merchants subscribed to the Starter plan, designed for small businesses and startups.",
  },
  proPlanMerchants: {
    title: "Pro Plan Merchants",
    description: "Number of merchants on the Pro plan with advanced features and higher usage limits.",
  },
  enterprisePlanMerchants: {
    title: "Enterprise Plan Merchants",
    description: "Number of merchants on custom Enterprise agreements with dedicated support and unlimited features.",
  },
  customPlanMerchants: {
    title: "Custom Plan Merchants",
    description: "Number of merchants with specially negotiated plans tailored to their specific requirements.",
  },
  totalMessages: {
    title: "Total Messages",
    description: "Cumulative count of all messages exchanged between customers and the support system (both AI and human responses).",
  },
  activeChats: {
    title: "Active Chats",
    description: "Number of chat sessions currently in progress with ongoing customer interactions.",
  },
  totalChats: {
    title: "Total Chats",
    description: "Total number of chat sessions including active, completed, and archived conversations.",
  },
  dailySubscriptions: {
    title: "Daily Subscriptions",
    description: "Number of new subscription sign-ups recorded today.",
  },
  weeklySubscriptions: {
    title: "Weekly Subscriptions",
    description: "Number of new subscription sign-ups in the past 7 days.",
  },
  monthlySubscriptions: {
    title: "Monthly Subscriptions",
    description: "Number of new subscription sign-ups in the past 30 days.",
  },
  yearlySubscriptions: {
    title: "Yearly Subscriptions",
    description: "Number of new subscription sign-ups in the past 12 months.",
  },
  overviewMetrics: {
    title: "Overview Metrics",
    description: "High-level dashboard showing key performance indicators including merchants, revenue, conversations, and platform health at a glance.",
  },
  dataUsageMetrics: {
    title: "Data Usage Metrics",
    description: "Detailed breakdown of platform resource consumption including bandwidth, storage, API calls, and message volume across all merchants.",
  },
};

export function getMetricInfo(key: string): MetricDefinition {
  return metricGlossary[key] || {
    title: key.replace(/([A-Z])/g, ' $1').trim(),
    description: "No description available for this metric.",
  };
}
