export { default as CustomerLoginPage } from "./login";
export { default as CustomerVerifyPage } from "./verify";
export { default as CustomerRegisterPage } from "./register";
export { default as CustomerInboxPage } from "./inbox";
export { default as CustomerStoresPage } from "./stores";
export { default as CustomerContactsPage } from "./contacts";
export { default as CustomerSettingsPage } from "./settings";
export { default as CustomerStoreChatPage } from "./store-chat";
export { default as CustomerPersonalChatPage } from "./personal-chat";
