import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { FileText } from "lucide-react";
import PublicPageLayout from "../public-layout";

export default function TermsOfServicePage() {
  const lastUpdated = "December 1, 2025";

  return (
    <PublicPageLayout>
      <section className="bg-purple-600 text-white py-16">
        <div className="max-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <Badge className="bg-white/20 text-white mb-4">
            <FileText className="w-3 h-3 mr-1" />
            Legal
          </Badge>
          <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
          <p className="text-purple-100">Last updated: {lastUpdated}</p>
        </div>
      </section>

      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <Card className="p-8 prose dark:prose-invert max-w-none">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using Chatvice ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these terms, you may not access the Service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              Chatvice is an AI-powered customer service chatbot platform that enables businesses to deploy AI agents for automated customer support. The Service includes:
            </p>
            <ul>
              <li>AI-powered chat agents (LEXA1 Engine)</li>
              <li>Embeddable chat widgets</li>
              <li>Knowledge base management</li>
              <li>Human escalation capabilities</li>
              <li>Analytics and reporting</li>
            </ul>

            <h2>3. User Accounts</h2>
            <h3>3.1 Registration</h3>
            <p>
              You must register for an account to use certain features. You agree to provide accurate information and keep it updated.
            </p>
            <h3>3.2 Account Security</h3>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.
            </p>
            <h3>3.3 Account Types</h3>
            <p>
              We offer Merchant accounts (for businesses) and Supervisor accounts (for support staff). Each has different access levels and capabilities.
            </p>

            <h2>4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service for any illegal purpose</li>
              <li>Upload malicious content or malware</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with other users' use of the Service</li>
              <li>Use the Service to send spam or unsolicited messages</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
            </ul>

            <h2>5. Content</h2>
            <h3>5.1 Your Content</h3>
            <p>
              You retain ownership of content you upload (knowledge base materials, configurations). You grant us a license to use this content to provide the Service.
            </p>
            <h3>5.2 Customer Data</h3>
            <p>
              Chat conversations and customer data collected through your agents are your responsibility. You must comply with applicable privacy laws.
            </p>
            <h3>5.3 AI-Generated Content</h3>
            <p>
              AI responses generated by LEXA1 are based on your knowledge base and configurations. You are responsible for reviewing and ensuring accuracy.
            </p>

            <h2>6. Payment Terms</h2>
            <h3>6.1 Subscription Plans</h3>
            <p>
              Paid features require a subscription. Pricing and features for each plan are available on our pricing page.
            </p>
            <h3>6.2 Billing</h3>
            <p>
              Subscriptions are billed in advance on a monthly or annual basis. Payment is processed through 1-Pay or other approved payment providers.
            </p>
            <h3>6.3 Refunds</h3>
            <p>
              Annual subscriptions include a 30-day money-back guarantee. Monthly subscriptions are non-refundable but can be cancelled anytime.
            </p>

            <h2>7. Service Level</h2>
            <p>
              We strive for 99.9% uptime for paid plans. Scheduled maintenance will be announced in advance when possible.
            </p>

            <h2>8. Intellectual Property</h2>
            <p>
              The Service, including LEXA1 AI Engine, is protected by intellectual property laws. You may not copy, modify, or reverse engineer any part of the Service.
            </p>

            <h2>9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Chatvice shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.
            </p>

            <h2>10. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Chatvice from any claims arising from your use of the Service or violation of these Terms.
            </p>

            <h2>11. Termination</h2>
            <p>
              We may terminate or suspend your account immediately for violations of these Terms. You may cancel your account at any time through account settings.
            </p>

            <h2>12. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will provide notice of significant changes via email or through the Service.
            </p>

            <h2>13. Governing Law</h2>
            <p>
              These Terms shall be governed by the laws of Indonesia, without regard to conflict of law provisions.
            </p>

            <h2>14. Contact</h2>
            <p>
              Questions about these Terms should be sent to: legal@chatvice.app
            </p>
          </Card>
        </div>
      </section>
    </PublicPageLayout>
  );
}
